import { PrismaClient, MembershipType, MembershipStatus, EventType, SkillLevel, GenderCategory } from '@prisma/client';

const prisma = new PrismaClient();

const samplePlayers = [
  {
    firstName: 'Sarah',
    lastName: 'Johnson',
    email: 'sarah.johnson@email.com',
    phone: '555-0101',
    membershipType: MembershipType.GOLD,
    membershipStatus: MembershipStatus.ACTIVE,
    classCredits: 0,
    dropInCredits: 0,
  },
  {
    firstName: 'Michael',
    lastName: 'Chen',
    email: 'michael.chen@email.com',
    phone: '555-0102',
    membershipType: MembershipType.DROP_IN,
    membershipStatus: MembershipStatus.ACTIVE,
    classCredits: 0,
    dropInCredits: 8,
  },
  {
    firstName: 'Emily',
    lastName: 'Rodriguez',
    email: 'emily.rodriguez@email.com',
    phone: '555-0103',
    membershipType: MembershipType.NONE,
    membershipStatus: MembershipStatus.ACTIVE,
    classCredits: 5,
    dropInCredits: 3,
  },
  {
    firstName: 'David',
    lastName: 'Kim',
    email: 'david.kim@email.com',
    phone: '555-0104',
    membershipType: MembershipType.GOLD,
    membershipStatus: MembershipStatus.PAUSED,
    classCredits: 0,
    dropInCredits: 0,
  },
  {
    firstName: 'Jessica',
    lastName: 'Williams',
    email: 'jessica.williams@email.com',
    phone: '555-0105',
    membershipType: MembershipType.DROP_IN,
    membershipStatus: MembershipStatus.ACTIVE,
    classCredits: 0,
    dropInCredits: 12,
  },
  {
    firstName: 'Chris',
    lastName: 'Anderson',
    email: 'chris.anderson@email.com',
    phone: '555-0106',
    membershipType: MembershipType.NONE,
    membershipStatus: MembershipStatus.ACTIVE,
    classCredits: 10,
    dropInCredits: 0,
  },
  {
    firstName: 'Amanda',
    lastName: 'Taylor',
    email: 'amanda.taylor@email.com',
    phone: '555-0107',
    membershipType: MembershipType.GOLD,
    membershipStatus: MembershipStatus.CANCELLED,
    classCredits: 0,
    dropInCredits: 0,
  },
  {
    firstName: 'Ryan',
    lastName: 'Martinez',
    email: 'ryan.martinez@email.com',
    phone: '555-0108',
    membershipType: MembershipType.NONE,
    membershipStatus: MembershipStatus.ACTIVE,
    classCredits: 2,
    dropInCredits: 5,
  },
  {
    firstName: 'Lauren',
    lastName: 'Brown',
    email: 'lauren.brown@email.com',
    phone: '555-0109',
    membershipType: MembershipType.DROP_IN,
    membershipStatus: MembershipStatus.PAUSED,
    classCredits: 0,
    dropInCredits: 4,
  },
  {
    firstName: 'Kevin',
    lastName: 'Lee',
    email: 'kevin.lee@email.com',
    phone: '555-0110',
    membershipType: MembershipType.GOLD,
    membershipStatus: MembershipStatus.ACTIVE,
    classCredits: 0,
    dropInCredits: 0,
  },
  {
    firstName: 'Nicole',
    lastName: 'Garcia',
    email: 'nicole.garcia@email.com',
    phone: '555-0111',
    membershipType: MembershipType.NONE,
    membershipStatus: MembershipStatus.ACTIVE,
    classCredits: 7,
    dropInCredits: 2,
  },
  {
    firstName: 'Brandon',
    lastName: 'Davis',
    email: 'brandon.davis@email.com',
    phone: '555-0112',
    membershipType: MembershipType.DROP_IN,
    membershipStatus: MembershipStatus.ACTIVE,
    classCredits: 0,
    dropInCredits: 15,
  },
];

// Events for weeks of Jan 11 and Jan 18, 2026
const sampleEvents = [
  // Week of Jan 11 (Sat-Sun)
  // Saturday Jan 11
  {
    title: 'Adult Level I',
    description: 'Beginner class for new players',
    eventType: EventType.CLASS,
    courtId: 1,
    startTime: new Date('2026-01-11T09:00:00'),
    endTime: new Date('2026-01-11T10:30:00'),
    maxCapacity: 12,
    instructor: 'Coach Mike',
    level: SkillLevel.INTRO_I,
    gender: GenderCategory.COED,
    isYouth: false,
  },
  {
    title: 'Adult Level II',
    description: 'Fundamentals and basic strategies',
    eventType: EventType.CLASS,
    courtId: 2,
    startTime: new Date('2026-01-11T09:00:00'),
    endTime: new Date('2026-01-11T10:30:00'),
    maxCapacity: 12,
    instructor: 'Coach Sarah',
    level: SkillLevel.INTRO_II,
    gender: GenderCategory.COED,
    isYouth: false,
  },
  {
    title: 'Adult Level III',
    description: 'Intermediate skills and game play',
    eventType: EventType.CLASS,
    courtId: 1,
    startTime: new Date('2026-01-11T11:00:00'),
    endTime: new Date('2026-01-11T12:30:00'),
    maxCapacity: 12,
    instructor: 'Coach Mike',
    level: SkillLevel.INTRO_III,
    gender: GenderCategory.COED,
    isYouth: false,
  },
  {
    title: 'Intermediate 2s',
    description: 'Open play for intermediate players - doubles format',
    eventType: EventType.OPEN_PLAY,
    courtId: 2,
    startTime: new Date('2026-01-11T11:00:00'),
    endTime: new Date('2026-01-11T13:00:00'),
    maxCapacity: 16,
    instructor: null,
    level: SkillLevel.INTERMEDIATE,
    gender: GenderCategory.COED,
    isYouth: false,
  },
  {
    title: 'Adult Level IV',
    description: 'Advanced fundamentals and competitive play',
    eventType: EventType.CLASS,
    courtId: 1,
    startTime: new Date('2026-01-11T13:00:00'),
    endTime: new Date('2026-01-11T14:30:00'),
    maxCapacity: 10,
    instructor: 'Coach Sarah',
    level: SkillLevel.INTRO_IV,
    gender: GenderCategory.COED,
    isYouth: false,
  },
  {
    title: 'Advanced 2s',
    description: 'Open play for advanced players - doubles format',
    eventType: EventType.OPEN_PLAY,
    courtId: 2,
    startTime: new Date('2026-01-11T13:00:00'),
    endTime: new Date('2026-01-11T15:00:00'),
    maxCapacity: 16,
    instructor: null,
    level: SkillLevel.ADVANCED,
    gender: GenderCategory.COED,
    isYouth: false,
  },

  // Sunday Jan 12
  {
    title: 'Sunday Skills',
    description: 'Mixed level skills clinic',
    eventType: EventType.CLASS,
    courtId: 1,
    startTime: new Date('2026-01-12T10:00:00'),
    endTime: new Date('2026-01-12T11:30:00'),
    maxCapacity: 14,
    instructor: 'Coach Mike',
    level: SkillLevel.INTRO_II,
    gender: GenderCategory.COED,
    isYouth: false,
  },
  {
    title: 'Intermediate 2s',
    description: 'Open play for intermediate players - doubles format',
    eventType: EventType.OPEN_PLAY,
    courtId: 2,
    startTime: new Date('2026-01-12T10:00:00'),
    endTime: new Date('2026-01-12T12:00:00'),
    maxCapacity: 20,
    instructor: null,
    level: SkillLevel.INTERMEDIATE,
    gender: GenderCategory.COED,
    isYouth: false,
  },
  {
    title: 'Advanced 2s',
    description: 'Open play for advanced players - doubles format',
    eventType: EventType.OPEN_PLAY,
    courtId: 1,
    startTime: new Date('2026-01-12T12:00:00'),
    endTime: new Date('2026-01-12T14:00:00'),
    maxCapacity: 16,
    instructor: null,
    level: SkillLevel.ADVANCED,
    gender: GenderCategory.COED,
    isYouth: false,
  },

  // Weekdays Jan 13-17
  // Monday Jan 13
  {
    title: 'Adult Level I',
    description: 'Beginner class for new players',
    eventType: EventType.CLASS,
    courtId: 1,
    startTime: new Date('2026-01-13T18:00:00'),
    endTime: new Date('2026-01-13T19:30:00'),
    maxCapacity: 12,
    instructor: 'Coach Sarah',
    level: SkillLevel.INTRO_I,
    gender: GenderCategory.COED,
    isYouth: false,
  },
  {
    title: 'Adult Level III',
    description: 'Intermediate skills and game play',
    eventType: EventType.CLASS,
    courtId: 2,
    startTime: new Date('2026-01-13T18:00:00'),
    endTime: new Date('2026-01-13T19:30:00'),
    maxCapacity: 12,
    instructor: 'Coach Mike',
    level: SkillLevel.INTRO_III,
    gender: GenderCategory.COED,
    isYouth: false,
  },
  {
    title: 'Intermediate 2s',
    description: 'Open play for intermediate players',
    eventType: EventType.OPEN_PLAY,
    courtId: 1,
    startTime: new Date('2026-01-13T19:30:00'),
    endTime: new Date('2026-01-13T21:30:00'),
    maxCapacity: 16,
    instructor: null,
    level: SkillLevel.INTERMEDIATE,
    gender: GenderCategory.COED,
    isYouth: false,
  },

  // Tuesday Jan 14
  {
    title: 'Adult Level II',
    description: 'Fundamentals and basic strategies',
    eventType: EventType.CLASS,
    courtId: 1,
    startTime: new Date('2026-01-14T18:00:00'),
    endTime: new Date('2026-01-14T19:30:00'),
    maxCapacity: 12,
    instructor: 'Coach Mike',
    level: SkillLevel.INTRO_II,
    gender: GenderCategory.COED,
    isYouth: false,
  },
  {
    title: 'Adult Level IV',
    description: 'Advanced fundamentals',
    eventType: EventType.CLASS,
    courtId: 2,
    startTime: new Date('2026-01-14T18:00:00'),
    endTime: new Date('2026-01-14T19:30:00'),
    maxCapacity: 10,
    instructor: 'Coach Sarah',
    level: SkillLevel.INTRO_IV,
    gender: GenderCategory.COED,
    isYouth: false,
  },
  {
    title: 'Advanced 2s',
    description: 'Open play for advanced players',
    eventType: EventType.OPEN_PLAY,
    courtId: 1,
    startTime: new Date('2026-01-14T19:30:00'),
    endTime: new Date('2026-01-14T21:30:00'),
    maxCapacity: 16,
    instructor: null,
    level: SkillLevel.ADVANCED,
    gender: GenderCategory.COED,
    isYouth: false,
  },

  // Wednesday Jan 15
  {
    title: 'Adult Level I',
    description: 'Beginner class for new players',
    eventType: EventType.CLASS,
    courtId: 1,
    startTime: new Date('2026-01-15T18:00:00'),
    endTime: new Date('2026-01-15T19:30:00'),
    maxCapacity: 12,
    instructor: 'Coach Mike',
    level: SkillLevel.INTRO_I,
    gender: GenderCategory.COED,
    isYouth: false,
  },
  {
    title: 'Intermediate 2s',
    description: 'Open play for intermediate players',
    eventType: EventType.OPEN_PLAY,
    courtId: 2,
    startTime: new Date('2026-01-15T18:00:00'),
    endTime: new Date('2026-01-15T20:00:00'),
    maxCapacity: 20,
    instructor: null,
    level: SkillLevel.INTERMEDIATE,
    gender: GenderCategory.COED,
    isYouth: false,
  },

  // Thursday Jan 16
  {
    title: 'Adult Level III',
    description: 'Intermediate skills and game play',
    eventType: EventType.CLASS,
    courtId: 1,
    startTime: new Date('2026-01-16T18:00:00'),
    endTime: new Date('2026-01-16T19:30:00'),
    maxCapacity: 12,
    instructor: 'Coach Sarah',
    level: SkillLevel.INTRO_III,
    gender: GenderCategory.COED,
    isYouth: false,
  },
  {
    title: 'Advanced 2s',
    description: 'Open play for advanced players',
    eventType: EventType.OPEN_PLAY,
    courtId: 2,
    startTime: new Date('2026-01-16T18:00:00'),
    endTime: new Date('2026-01-16T20:00:00'),
    maxCapacity: 16,
    instructor: null,
    level: SkillLevel.ADVANCED,
    gender: GenderCategory.COED,
    isYouth: false,
  },

  // Week of Jan 18 (Sat-Sun)
  // Saturday Jan 18
  {
    title: 'Adult Level I',
    description: 'Beginner class for new players',
    eventType: EventType.CLASS,
    courtId: 1,
    startTime: new Date('2026-01-18T09:00:00'),
    endTime: new Date('2026-01-18T10:30:00'),
    maxCapacity: 12,
    instructor: 'Coach Mike',
    level: SkillLevel.INTRO_I,
    gender: GenderCategory.COED,
    isYouth: false,
  },
  {
    title: 'Adult Level II',
    description: 'Fundamentals and basic strategies',
    eventType: EventType.CLASS,
    courtId: 2,
    startTime: new Date('2026-01-18T09:00:00'),
    endTime: new Date('2026-01-18T10:30:00'),
    maxCapacity: 12,
    instructor: 'Coach Sarah',
    level: SkillLevel.INTRO_II,
    gender: GenderCategory.COED,
    isYouth: false,
  },
  {
    title: 'Adult Level III',
    description: 'Intermediate skills and game play',
    eventType: EventType.CLASS,
    courtId: 1,
    startTime: new Date('2026-01-18T11:00:00'),
    endTime: new Date('2026-01-18T12:30:00'),
    maxCapacity: 12,
    instructor: 'Coach Mike',
    level: SkillLevel.INTRO_III,
    gender: GenderCategory.COED,
    isYouth: false,
  },
  {
    title: 'Intermediate 2s',
    description: 'Open play for intermediate players - doubles format',
    eventType: EventType.OPEN_PLAY,
    courtId: 2,
    startTime: new Date('2026-01-18T11:00:00'),
    endTime: new Date('2026-01-18T13:00:00'),
    maxCapacity: 16,
    instructor: null,
    level: SkillLevel.INTERMEDIATE,
    gender: GenderCategory.COED,
    isYouth: false,
  },
  {
    title: 'Adult Level IV',
    description: 'Advanced fundamentals and competitive play',
    eventType: EventType.CLASS,
    courtId: 1,
    startTime: new Date('2026-01-18T13:00:00'),
    endTime: new Date('2026-01-18T14:30:00'),
    maxCapacity: 10,
    instructor: 'Coach Sarah',
    level: SkillLevel.INTRO_IV,
    gender: GenderCategory.COED,
    isYouth: false,
  },
  {
    title: 'Advanced 2s',
    description: 'Open play for advanced players - doubles format',
    eventType: EventType.OPEN_PLAY,
    courtId: 2,
    startTime: new Date('2026-01-18T13:00:00'),
    endTime: new Date('2026-01-18T15:00:00'),
    maxCapacity: 16,
    instructor: null,
    level: SkillLevel.ADVANCED,
    gender: GenderCategory.COED,
    isYouth: false,
  },

  // Sunday Jan 19
  {
    title: 'Sunday Skills',
    description: 'Mixed level skills clinic',
    eventType: EventType.CLASS,
    courtId: 1,
    startTime: new Date('2026-01-19T10:00:00'),
    endTime: new Date('2026-01-19T11:30:00'),
    maxCapacity: 14,
    instructor: 'Coach Mike',
    level: SkillLevel.INTRO_II,
    gender: GenderCategory.COED,
    isYouth: false,
  },
  {
    title: 'Intermediate 2s',
    description: 'Open play for intermediate players - doubles format',
    eventType: EventType.OPEN_PLAY,
    courtId: 2,
    startTime: new Date('2026-01-19T10:00:00'),
    endTime: new Date('2026-01-19T12:00:00'),
    maxCapacity: 20,
    instructor: null,
    level: SkillLevel.INTERMEDIATE,
    gender: GenderCategory.COED,
    isYouth: false,
  },
  {
    title: 'Advanced 2s',
    description: 'Open play for advanced players - doubles format',
    eventType: EventType.OPEN_PLAY,
    courtId: 1,
    startTime: new Date('2026-01-19T12:00:00'),
    endTime: new Date('2026-01-19T14:00:00'),
    maxCapacity: 16,
    instructor: null,
    level: SkillLevel.ADVANCED,
    gender: GenderCategory.COED,
    isYouth: false,
  },

  // Weekdays Jan 20-24
  // Monday Jan 20
  {
    title: 'Adult Level I',
    description: 'Beginner class for new players',
    eventType: EventType.CLASS,
    courtId: 1,
    startTime: new Date('2026-01-20T18:00:00'),
    endTime: new Date('2026-01-20T19:30:00'),
    maxCapacity: 12,
    instructor: 'Coach Sarah',
    level: SkillLevel.INTRO_I,
    gender: GenderCategory.COED,
    isYouth: false,
  },
  {
    title: 'Adult Level III',
    description: 'Intermediate skills and game play',
    eventType: EventType.CLASS,
    courtId: 2,
    startTime: new Date('2026-01-20T18:00:00'),
    endTime: new Date('2026-01-20T19:30:00'),
    maxCapacity: 12,
    instructor: 'Coach Mike',
    level: SkillLevel.INTRO_III,
    gender: GenderCategory.COED,
    isYouth: false,
  },
  {
    title: 'Intermediate 2s',
    description: 'Open play for intermediate players',
    eventType: EventType.OPEN_PLAY,
    courtId: 1,
    startTime: new Date('2026-01-20T19:30:00'),
    endTime: new Date('2026-01-20T21:30:00'),
    maxCapacity: 16,
    instructor: null,
    level: SkillLevel.INTERMEDIATE,
    gender: GenderCategory.COED,
    isYouth: false,
  },

  // Tuesday Jan 21
  {
    title: 'Adult Level II',
    description: 'Fundamentals and basic strategies',
    eventType: EventType.CLASS,
    courtId: 1,
    startTime: new Date('2026-01-21T18:00:00'),
    endTime: new Date('2026-01-21T19:30:00'),
    maxCapacity: 12,
    instructor: 'Coach Mike',
    level: SkillLevel.INTRO_II,
    gender: GenderCategory.COED,
    isYouth: false,
  },
  {
    title: 'Adult Level IV',
    description: 'Advanced fundamentals',
    eventType: EventType.CLASS,
    courtId: 2,
    startTime: new Date('2026-01-21T18:00:00'),
    endTime: new Date('2026-01-21T19:30:00'),
    maxCapacity: 10,
    instructor: 'Coach Sarah',
    level: SkillLevel.INTRO_IV,
    gender: GenderCategory.COED,
    isYouth: false,
  },
  {
    title: 'Advanced 2s',
    description: 'Open play for advanced players',
    eventType: EventType.OPEN_PLAY,
    courtId: 1,
    startTime: new Date('2026-01-21T19:30:00'),
    endTime: new Date('2026-01-21T21:30:00'),
    maxCapacity: 16,
    instructor: null,
    level: SkillLevel.ADVANCED,
    gender: GenderCategory.COED,
    isYouth: false,
  },

  // Wednesday Jan 22
  {
    title: 'Adult Level I',
    description: 'Beginner class for new players',
    eventType: EventType.CLASS,
    courtId: 1,
    startTime: new Date('2026-01-22T18:00:00'),
    endTime: new Date('2026-01-22T19:30:00'),
    maxCapacity: 12,
    instructor: 'Coach Mike',
    level: SkillLevel.INTRO_I,
    gender: GenderCategory.COED,
    isYouth: false,
  },
  {
    title: 'Intermediate 2s',
    description: 'Open play for intermediate players',
    eventType: EventType.OPEN_PLAY,
    courtId: 2,
    startTime: new Date('2026-01-22T18:00:00'),
    endTime: new Date('2026-01-22T20:00:00'),
    maxCapacity: 20,
    instructor: null,
    level: SkillLevel.INTERMEDIATE,
    gender: GenderCategory.COED,
    isYouth: false,
  },

  // Thursday Jan 23
  {
    title: 'Adult Level III',
    description: 'Intermediate skills and game play',
    eventType: EventType.CLASS,
    courtId: 1,
    startTime: new Date('2026-01-23T18:00:00'),
    endTime: new Date('2026-01-23T19:30:00'),
    maxCapacity: 12,
    instructor: 'Coach Sarah',
    level: SkillLevel.INTRO_III,
    gender: GenderCategory.COED,
    isYouth: false,
  },
  {
    title: 'Advanced 2s',
    description: 'Open play for advanced players',
    eventType: EventType.OPEN_PLAY,
    courtId: 2,
    startTime: new Date('2026-01-23T18:00:00'),
    endTime: new Date('2026-01-23T20:00:00'),
    maxCapacity: 16,
    instructor: null,
    level: SkillLevel.ADVANCED,
    gender: GenderCategory.COED,
    isYouth: false,
  },
];

async function main() {
  console.log('Seeding database...');

  // Seed players
  console.log('Seeding players...');
  for (const player of samplePlayers) {
    await prisma.player.upsert({
      where: { email: player.email },
      update: player,
      create: player,
    });
  }
  console.log(`Seeded ${samplePlayers.length} players.`);

  // Delete existing events first
  console.log('Clearing existing events...');
  await prisma.enrollment.deleteMany({});
  await prisma.event.deleteMany({});

  // Seed events
  console.log('Seeding events...');
  for (const event of sampleEvents) {
    await prisma.event.create({
      data: event,
    });
  }
  console.log(`Seeded ${sampleEvents.length} events.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
